services:

  # Local services are available on their ports, but also available on:
  # http://api.localhost.tiangolo.com: backend
  # http://dashboard.localhost.tiangolo.com: frontend
  # etc. To enable it, update .env, set:
  # DOMAIN=localhost.tiangolo.com
  proxy:
    image: traefik:3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "17801:80"
      - "17890:8080"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic/
      - --entrypoints.web.address=:80
      - --api
      - --api.dashboard=true
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$GQUXqJzr$$qxA5ZBDy3hKNJqXgzGxwX.
      - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-public-http.entrypoints=web
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-http.service=api@internal

  db:
    ports:
      - "17432:5432"

  adminer:
    ports:
      - "17080:8080"

  backend:
    ports:
      - "17010:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=local
      - FRONTEND_HOST=http://localhost:19100
      - BACKEND_CORS_ORIGINS=["http://localhost:19100","http://localhost:3000","http://localhost:17080","http://localhost:17010","http://localhost","https://localhost","https://localhost:19100","https://localhost:3000","https://localhost:17080","https://counselor-ai.cc"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "18080:1080"
      - "18025:1025"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "19100:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://counselor-ai.cc
      - NODE_ENV=production
    command: npm run dev -- --host 0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.app-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.app-frontend.loadbalancer.server.port=5173

  playwright:
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - mailcatcher
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      # For the reports when run locally
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports:
      - 19323:9323

networks:
  default:
    name: ${STACK_NAME?Variable not set}-default
  traefik-public:
    name: ${STACK_NAME?Variable not set}-traefik-public
